name: Backstop Action

on:
  push:
    branches:
    - master
    
jobs:
  build:
    name: backstop reference
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: install backstopjs
        run: npm install --force -g backstopjs
      - name: run backstop reference
        run: backstop reference
      - name: run backstop test
        run: backstop test
      - name: Archive HTML Report on failure
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: report
          path: backstop_data/
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.10
        with:
         # Artifact name
         name: Download report
         # Destination path
         path: backstop_data
      
